### ISSUE TITLE
ip2location i/o timeout

### ISSUE THREAD

**Issue by vitich** [ip2location/logstash-filter-ip2location#3]
Hi!
Usually I use standard geoip, but have decided to test ip2location for comparison.
When I add ip2location, my ELK server doesn't receive the log from heavy load nginx server.
Less loaded servers continue to transfer the log
When I remove this plugin - everything is OK

Filebeat log:
```
ERR Failed to publish events (host: 10.10.10.17:5044:10200), caused by: read tcp 10.2.2.6:10911->10.120.12.117:5044: i/o timeout
2018-03-22T13:26:49Z INFO Error publishing events (retrying): read tcp 10.2.2.6:10911->10.10.10.17:5044: i/o timeout

```

elasticsearch-5.6.8-1.noarch
logstash-5.6.8-1.noarch
kibana-5.6.8-1.x86_64
filebeat-5.6.6-1.x86_64

# cat /etc/logstash/conf.d/22-nginx-upstream.conf 
```
filter {
  if [type] == "nginx_upstream" {
    grok {
      patterns_dir => ["/etc/logstash/conf.d/patterns/nginx"]
      match => { "message" => "%{NGINX_ACCESS_UPSTREAM}" }
    }
    date {
      match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z", "dd/MMM/yyyy:HH:mm:ssZ", "ISO8601" ]
      target => "@timestamp"
    }
    geoip {
      source => "clientip"
      database => "/usr/local/share/GeoIP/GeoLite2-City.mmdb"
    }
    ip2location {
      source => "clientip"
      database => "/etc/logstash/IP2LOCATION-LITE-DB11.BIN"
    }
    useragent {
      source => "browser-name"
    }
    mutate { 
      remove_field => "@version"
      remove_field => "input_type"
      remove_field => "[beat]"
      remove_field => "[geoip][continent_code]"
      remove_field => "[geoip][country_code3]"
      remove_field => "[geoip][ip]"
      remove_field => "[geoip][latitude]"
      remove_field => "[geoip][longitude]"
      remove_field => "[geoip][postal_code]"
      remove_field => "[geoip][region_code]"
      remove_field => "[geoip][region_name]"
      remove_field => "[geoip][timezone]"
      remove_field => "offset"
      remove_field => "timestamp"
    }
  }
}
```
# cat /etc/filebeat/filebeat.yml 
```
filebeat.modules:
filebeat.prospectors:
- input_type: log
  paths:
    - /var/virtual/example.com/logs/upstream_access_log
  document_type: nginx_upstream
- input_type: log
  paths:
    - /var/virtual/example.com/logs/upstream_error_log
  document_type: nginx_error
- input_type: log
  paths:
    - /var/virtual/new/logs/access_log
  document_type: nginx_upstream
- input_type: log
  paths:
    - /var/virtual/new/logs/error_log
  document_type: nginx_error
output.logstash:
  enabled: true
#  bulk_max_size: 800
  hosts: ["10.120.12.117:5044"]
logging.level: info
```
